etapas: 
    - nome: gcr.io/cloud-builders/docker 
      args: ['build', '-t', 'gcr.io/$PROJECT_ID/singularity-api-auth:${SHORT_SHA}', '.']
    - nome: 'gcr.io/cloud-builders/docker' 
      args: ["push", "gcr.io/$PROJECT_ID/singularity-api-auth"]