
    steps:
        # build the container image
      - name: 'gcr.io/cloud-builders/docker'
        args: ['build', '-t', 'gcr.io/$PROJECT_ID/singularity-api-auth:${SHORT_SHA}', '.']
        # push the container image to Container Registry
      - name: 'gcr.io/cloud-builders/docker'
        args: ['push', 'gcr.io/$PROJECT_ID/singularity-api-auth']
        # deploy container image to Cloud Run
      - name: 'gcr.io/cloud-builders/gcloud'
        args: ['beta', 'run', 'deploy', 'singularity-api-auth', '--image', 'gcr.io/$PROJECT_ID/singularity-api-auth:${SHORT_SHA}', '--region', 'us-central1', '--allow-unauthenticated']
        env:
        - 'PORT=8080'
      images:
      - gcr.io/$PROJECT_ID/singularity-api-auth